import { offsetCoords } from '../geo';
import { Coords, MealPeriod, OpenInterval, Place, WeeklyHours } from '../types';

/** `h(9, 30)` → minutes since midnight. Values past 24 mean "after midnight". */
const h = (hour: number, minute = 0) => hour * 60 + minute;

const every = (...slots: OpenInterval[]): WeeklyHours => Array.from({ length: 7 }, () => slots);

/** Same hours all week, but closed on the given weekday indices. */
const exceptOn = (closed: number[], ...slots: OpenInterval[]): WeeklyHours =>
  Array.from({ length: 7 }, (_, day) => (closed.includes(day) ? [] : slots));

/** Weekdays vs weekend (Sat = 6, Sun = 0). */
const split = (weekday: OpenInterval[], weekend: OpenInterval[]): WeeklyHours =>
  Array.from({ length: 7 }, (_, day) => (day === 0 || day === 6 ? weekend : weekday));

interface Seed extends Omit<Place, 'id' | 'coords' | 'address'> {
  /** Metres from the user. */
  away: number;
  /** Compass bearing, so the sample map reads as a real neighbourhood. */
  bearing: number;
  street: string;
}

const IMG = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=70`;

/**
 * A hand-built neighbourhood. It is laid out relative to wherever the user
 * actually is, so the app is fully explorable without any API key — and the
 * ranking, hours and distance logic all exercise real code paths.
 */
const SEEDS: Seed[] = [
  {
    name: 'Mercer & Vine',
    cuisine: 'Wood-fired seasonal',
    tags: ['Wood fire', 'Natural wine', 'Small plates'],
    rating: 4.8,
    reviewCount: 1840,
    priceLevel: 3,
    photo: IMG('photo-1517248135467-4c7edcad34c4'),
    hours: exceptOn([1], { open: h(17, 30), close: h(23) }),
    mealPeriods: ['dinner'],
    typicalWait: 25,
    away: 480,
    bearing: 42,
    street: '18 Mercer Lane',
  },
  {
    name: 'Kanda Ramen Bar',
    cuisine: 'Tonkotsu ramen',
    tags: ['Counter seating', 'Solo-friendly', 'Quick'],
    rating: 4.7,
    reviewCount: 2610,
    priceLevel: 2,
    photo: IMG('photo-1569718212165-3a8278d5f624'),
    hours: every({ open: h(11, 30), close: h(14, 30) }, { open: h(17), close: h(25) }),
    mealPeriods: ['lunch', 'dinner', 'late'],
    typicalWait: 10,
    away: 310,
    bearing: 155,
    street: '4 Kanda Passage',
  },
  {
    name: 'Fig & Ash',
    cuisine: 'Bakery & all-day café',
    tags: ['Pastry', 'Filter coffee', 'Laptop-friendly'],
    rating: 4.6,
    reviewCount: 980,
    priceLevel: 1,
    photo: IMG('photo-1509440159596-0249088772ff'),
    hours: every({ open: h(7), close: h(16) }),
    mealPeriods: ['breakfast', 'brunch', 'coffee'],
    typicalWait: 5,
    away: 220,
    bearing: 300,
    street: '91 Ash Street',
    vegetarianFriendly: true,
  },
  {
    name: 'Casa Nueve',
    cuisine: 'Mexico City taqueria',
    tags: ['Al pastor', 'Late kitchen', 'Standing room'],
    rating: 4.7,
    reviewCount: 3420,
    priceLevel: 1,
    photo: IMG('photo-1565299585323-38d6b0865b47'),
    hours: every({ open: h(12), close: h(26) }),
    mealPeriods: ['lunch', 'dinner', 'late'],
    typicalWait: 8,
    away: 640,
    bearing: 210,
    street: '9 Calle Norte',
  },
  {
    name: 'The Long Table',
    cuisine: 'Modern British',
    tags: ['Set lunch', 'Quiet room', 'Good for two'],
    rating: 4.5,
    reviewCount: 720,
    priceLevel: 3,
    photo: IMG('photo-1552566626-52f8b828add9'),
    hours: exceptOn([0], { open: h(12), close: h(15) }, { open: h(18), close: h(22, 30) }),
    mealPeriods: ['lunch', 'dinner'],
    typicalWait: 15,
    away: 900,
    bearing: 15,
    street: '2 Guild Square',
  },
  {
    name: 'Sunday Egg Club',
    cuisine: 'Brunch',
    tags: ['Eggs', 'Bottomless coffee', 'Terrace'],
    rating: 4.4,
    reviewCount: 1560,
    priceLevel: 2,
    photo: IMG('photo-1476224203421-9ac39bcb3327'),
    hours: every({ open: h(8), close: h(15) }),
    mealPeriods: ['breakfast', 'brunch'],
    typicalWait: 20,
    away: 540,
    bearing: 120,
    street: '33 Poplar Road',
    vegetarianFriendly: true,
  },
  {
    name: 'Nonna Rosa',
    cuisine: 'Neapolitan pizza',
    tags: ['Sourdough base', 'Family-run', 'Takeaway'],
    rating: 4.6,
    reviewCount: 2240,
    priceLevel: 2,
    photo: IMG('photo-1565299624946-b28f40a0ae38'),
    hours: every({ open: h(12), close: h(23) }),
    mealPeriods: ['lunch', 'dinner', 'late'],
    typicalWait: 12,
    away: 760,
    bearing: 265,
    street: '7 Bell Court',
    vegetarianFriendly: true,
  },
  {
    name: 'Green Room',
    cuisine: 'Vegetarian bowls',
    tags: ['Seasonal', 'Fast', 'Gluten-free options'],
    rating: 4.5,
    reviewCount: 640,
    priceLevel: 2,
    photo: IMG('photo-1546069901-ba9599a7e63c'),
    hours: split([{ open: h(11), close: h(20) }], [{ open: h(11), close: h(17) }]),
    mealPeriods: ['lunch', 'dinner'],
    typicalWait: 4,
    away: 390,
    bearing: 80,
    street: '12 Willow Walk',
    vegetarianFriendly: true,
  },
  {
    name: 'Halden Coffee',
    cuisine: 'Specialty coffee',
    tags: ['Single origin', 'Cardamom bun', 'Small'],
    rating: 4.8,
    reviewCount: 410,
    priceLevel: 1,
    photo: IMG('photo-1554118811-1e0d58224f24'),
    hours: every({ open: h(7, 30), close: h(17) }),
    mealPeriods: ['breakfast', 'coffee'],
    typicalWait: 3,
    away: 170,
    bearing: 350,
    street: '5 Halden Yard',
    vegetarianFriendly: true,
  },
  {
    name: 'Sixteen Spices',
    cuisine: 'South Indian',
    tags: ['Dosa', 'Thali', 'Vegetarian kitchen'],
    rating: 4.7,
    reviewCount: 1980,
    priceLevel: 2,
    photo: IMG('photo-1585032226651-759b368d7246'),
    hours: exceptOn([2], { open: h(11, 30), close: h(22) }),
    mealPeriods: ['lunch', 'dinner'],
    typicalWait: 10,
    away: 1100,
    bearing: 190,
    street: '48 Spice Market',
    vegetarianFriendly: true,
  },
  {
    name: 'Blue Hour Bistro',
    cuisine: 'French bistro',
    tags: ['Steak frites', 'Late seating', 'Bar dining'],
    rating: 4.5,
    reviewCount: 1320,
    priceLevel: 3,
    photo: IMG('photo-1414235077428-338989a2e8c0'),
    hours: every({ open: h(18), close: h(24) }),
    mealPeriods: ['dinner', 'late'],
    typicalWait: 18,
    away: 820,
    bearing: 330,
    street: '21 Rue Verte',
  },
  {
    name: 'Sam’s Counter',
    cuisine: 'Smash burgers',
    tags: ['Under 10 min', 'Takeaway', 'Open late'],
    rating: 4.4,
    reviewCount: 2870,
    priceLevel: 1,
    photo: IMG('photo-1568901346375-23c9450c58cd'),
    hours: every({ open: h(11), close: h(27) }),
    mealPeriods: ['lunch', 'dinner', 'late'],
    typicalWait: 5,
    away: 450,
    bearing: 240,
    street: '3 Dock Street',
  },
  {
    name: 'Aegean Table',
    cuisine: 'Greek meze',
    tags: ['Sharing', 'Groups', 'Grilled fish'],
    rating: 4.6,
    reviewCount: 890,
    priceLevel: 2,
    photo: IMG('photo-1600891964092-4316c288032e'),
    hours: exceptOn([1], { open: h(12), close: h(23) }),
    mealPeriods: ['lunch', 'dinner'],
    typicalWait: 14,
    away: 1350,
    bearing: 60,
    street: '60 Harbour Row',
    vegetarianFriendly: true,
  },
  {
    name: 'Oat & Anchor',
    cuisine: 'Breakfast counter',
    tags: ['Porridge', 'Opens at six', 'Commuter'],
    rating: 4.3,
    reviewCount: 520,
    priceLevel: 1,
    photo: IMG('photo-1533089860892-a7c6f0a88666'),
    hours: split([{ open: h(6), close: h(12) }], [{ open: h(8), close: h(13) }]),
    mealPeriods: ['breakfast'],
    typicalWait: 3,
    away: 280,
    bearing: 20,
    street: '1 Anchor Lane',
    vegetarianFriendly: true,
  },
  {
    name: 'Hanoi Corner',
    cuisine: 'Vietnamese',
    tags: ['Pho', 'Banh mi', 'Cash-friendly'],
    rating: 4.6,
    reviewCount: 1740,
    priceLevel: 1,
    photo: IMG('photo-1582878826629-29b7ad1cdc43'),
    hours: every({ open: h(10), close: h(21) }),
    mealPeriods: ['breakfast', 'lunch', 'dinner'],
    typicalWait: 6,
    away: 620,
    bearing: 285,
    street: '14 Trellis Street',
  },
  {
    name: 'Midnight Diner',
    cuisine: 'All-night diner',
    tags: ['24 hours', 'Booths', 'Pancakes at 3am'],
    rating: 4.2,
    reviewCount: 3050,
    priceLevel: 1,
    photo: IMG('photo-1550966871-3ed3cdb5ed0c'),
    hours: every({ open: h(0), close: h(24) }),
    mealPeriods: ['breakfast', 'lunch', 'dinner', 'late'],
    typicalWait: 5,
    away: 980,
    bearing: 140,
    street: '77 Night Street',
  },
  {
    name: 'Tessellate',
    cuisine: 'Tasting menu',
    tags: ['Chef’s counter', 'Booking only', 'Occasion'],
    rating: 4.9,
    reviewCount: 460,
    priceLevel: 4,
    photo: IMG('photo-1504674900247-0877df9cc836'),
    hours: exceptOn([0, 1, 2], { open: h(18, 30), close: h(22) }),
    mealPeriods: ['dinner'],
    typicalWait: 0,
    away: 1500,
    bearing: 100,
    street: '30 Foundry Way',
  },
  {
    name: 'Pastelaria Dez',
    cuisine: 'Portuguese pastry',
    tags: ['Custard tarts', 'Stand-up counter', 'Cheap'],
    rating: 4.7,
    reviewCount: 1130,
    priceLevel: 1,
    photo: IMG('photo-1559339352-11d035aa65de'),
    hours: every({ open: h(7), close: h(19) }),
    mealPeriods: ['breakfast', 'coffee'],
    typicalWait: 4,
    away: 700,
    bearing: 315,
    street: '10 Dez Arcade',
    vegetarianFriendly: true,
  },
];

/** Builds the sample neighbourhood around a given origin. */
export function samplePlaces(origin: Coords): Place[] {
  return SEEDS.map((seed, index) => {
    const { away, bearing, street, ...rest } = seed;
    return {
      ...rest,
      id: `sample-${index}`,
      coords: offsetCoords(origin, away, bearing),
      address: street,
    } satisfies Place;
  });
}

export const SAMPLE_MEAL_PERIODS: MealPeriod[] = [
  'breakfast',
  'brunch',
  'lunch',
  'coffee',
  'dinner',
  'late',
];
